name: "nipponia"
services:
  bi:
    networks:
      "docker.local":
        ipv4_address: 172.30.0.51
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/nipponia/bi/storage:/var/www/html/storage
      - /var/www/nipponia/bi/.env:/var/www/html/.env
    deploy:
      restart_policy:
        condition: always
networks:
  "docker.local":
    external: true
    name: "docker.local"